name: release
on:
  release:
    types:
      - released

jobs:
  finalize-sentry-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          sentry-cli --version

      - name: Configure SENTRY env vars
        run:
          node ./build/configure-sentry.js >> $GITHUB_ENV
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Finalize the Sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: protocol-labs-ip
          SENTRY_PROJECT: filecoin-station
        run: sentry-cli releases finalize "${{ env.SENTRY_VERSION }}"
